
PULMONIC_CONSONANTS = [
  { letter: "m̥", features: %w{pulmonic voiceless bilabial nasal} },
  { letter: "m", features: %w{pulmonic voiced bilabial nasal} },
  { letter: "ɱ", features: %w{pulmonic voiced labio_dental nasal} },
  { letter: "n̪", features: %w{pulmonic voiced dental nasal} },
  { letter: "n̥", features: %w{pulmonic voiceless alveolar nasal} },
  { letter: "n", features: %w{pulmonic voiced alveolar nasal} },
  { letter: "n̠", features: %w{pulmonic voiced post_alveolar nasal} },
  { letter: "ɳ̊", features: %w{pulmonic voiceless retroflex nasal} },
  { letter: "ɳ", features: %w{pulmonic voiced retroflex nasal} },
  { letter: "ɲ̟", features: %w{pulmonic voiced alveolo_palatal nasal} },
  { letter: "ɲ̊", features: %w{pulmonic voiceless palatal nasal} },
  { letter: "ɲ", features: %w{pulmonic voiced palatal nasal} },
  { letter: "ŋ̊", features: %w{pulmonic voiceless velar nasal} },
  { letter: "ŋ", features: %w{pulmonic voiced velar nasal} },
  { letter: "ɴ", features: %w{pulmonic voiced uvular nasal} },
  { letter: "p", features: %w{pulmonic voiceless bilabial stop} },
  { letter: "b", features: %w{pulmonic voiced bilabial stop} },
  { letter: "p̪", features: %w{pulmonic voiceless labio_dental stop} },
  { letter: "b̪", features: %w{pulmonic voiced labio_dental stop} },
  { letter: "t̪", features: %w{pulmonic voiceless dental stop} },
  { letter: "d̪", features: %w{pulmonic voiced dental stop} },
  { letter: "t", features: %w{pulmonic voiceless alveolar stop} },
  { letter: "d", features: %w{pulmonic voiced alveolar stop} },
  { letter: "ʈ", features: %w{pulmonic voiceless retroflex stop} },
  { letter: "ɖ", features: %w{pulmonic voiced retroflex stop} },
  { letter: "c", features: %w{pulmonic voiceless palatal stop} },
  { letter: "ɟ", features: %w{pulmonic voiced palatal stop} },
  { letter: "k", features: %w{pulmonic voiceless velar stop} },
  { letter: "ɡ", features: %w{pulmonic voiced velar stop} },
  { letter: "q", features: %w{pulmonic voiceless uvular stop} },
  { letter: "ɢ", features: %w{pulmonic voiced uvular stop} },
  { letter: "ʡ", features: %w{pulmonic epiglottal stop} },
  { letter: "ʔ", features: %w{pulmonic voiceless glottal stop} },
  { letter: "s̪", features: %w{pulmonic voiceless dental sibilant fricative} },
  { letter: "z̪", features: %w{pulmonic voiced dental sibilant fricative} },
  { letter: "s", features: %w{pulmonic voiceless alveolar sibilant fricative} },
  { letter: "z", features: %w{pulmonic voiced alveolar sibilant fricative} },
  { letter: "ʃ", features: %w{pulmonic voiceless post_alveolar sibilant fricative} },
  { letter: "ʒ", features: %w{pulmonic voiced post_alveolar sibilant fricative} },
  { letter: "ʂ", features: %w{pulmonic voiceless retroflex sibilant fricative} },
  { letter: "ʐ", features: %w{pulmonic voiced retroflex sibilant fricative} },
  { letter: "ɕ", features: %w{pulmonic voiceless alveolo_palatal sibilant fricative} },
  { letter: "ʑ", features: %w{pulmonic voiced alveolo_palatal sibilant fricative} },
  { letter: "ɸ", features: %w{pulmonic voiceless bilabial fricative} },
  { letter: "β", features: %w{pulmonic voiced bilabial fricative} },
  { letter: "f", features: %w{pulmonic voiceless labio_dental fricative} },
  { letter: "v", features: %w{pulmonic voiced labio_dental fricative} },
  { letter: "θ", features: %w{pulmonic voiceless dental fricative} },
  { letter: "ð", features: %w{pulmonic voiced dental fricative} },
  { letter: "θ̱", features: %w{pulmonic voiceless alveolar fricative} },
  { letter: "ð̠", features: %w{pulmonic voiced alveolar fricative} },
  { letter: "ç", features: %w{pulmonic voiceless palatal fricative} },
  { letter: "ʝ", features: %w{pulmonic voiced palatal fricative} },
  { letter: "x", features: %w{pulmonic voiceless velar fricative} },
  { letter: "ɣ", features: %w{pulmonic voiced velar fricative} },
  { letter: "χ", features: %w{pulmonic voiceless uvular fricative} },
  { letter: "ʁ", features: %w{pulmonic voiced uvular fricative} },
  { letter: "ħ", features: %w{pulmonic voiceless pharyngeal fricative} },
  { letter: "ʕ", features: %w{pulmonic voiced pharyngeal fricative} },
  { letter: "ʜ", features: %w{pulmonic voiceless epiglottal fricative} },
  { letter: "ʢ", features: %w{pulmonic voiced epiglottal fricative} },
  { letter: "h", features: %w{pulmonic voiceless glottal fricative} },
  { letter: "ɦ", features: %w{pulmonic voiced glottal fricative} },
  { letter: "ʋ", features: %w{pulmonic voiced labio_dental approximant} },
  { letter: "ɹ", features: %w{pulmonic voiced alveolar approximant} },
  { letter: "ɻ", features: %w{pulmonic voiced retroflex approximant} },
  { letter: "j̊", features: %w{pulmonic voiceless palatal approximant} },
  { letter: "j", features: %w{pulmonic voiced palatal approximant} },
  { letter: "ɰ", features: %w{pulmonic voiced velar approximant} },
  { letter: "ⱱ̟", features: %w{pulmonic voiced bilabial flap} },
  { letter: "ⱱ", features: %w{pulmonic voiced labio_dental flap} },
  { letter: "ɾ", features: %w{pulmonic voiced alveolar flap} },
  { letter: "ɽ", features: %w{pulmonic voiced retroflex flap} },
  { letter: "ɢ̆", features: %w{pulmonic voiced uvular flap} },
  { letter: "ʡ̯", features: %w{pulmonic voiced epiglottal flap} },
  { letter: "ʙ", features: %w{pulmonic voiced bilabial trill} },
  { letter: "r̥", features: %w{pulmonic voiceless alveolar trill} },
  { letter: "r", features: %w{pulmonic voiced alveolar trill} },
  { letter: "ɽ͡r", features: %w{pulmonic voiced retroflex trill} },
  { letter: "ʀ", features: %w{pulmonic voiced uvular trill} },
  { letter: "ᴙ ", features: %w{pulmonic voiced epiglottal trill} },
  { letter: "ɬ", features: %w{pulmonic voiceless alveolar lateral fricative} },
  { letter: "ɮ", features: %w{pulmonic voiced alveolar lateral fricative} },
  { letter: "ɬ̢", features: %w{pulmonic voiceless post_alveolar lateral fricative } },
  { letter: "ʎ̝̊", features: %w{pulmonic voiceless palatal lateral fricative} },
  { letter: "ʟ̝̊", features: %w{pulmonic voiceless velar lateral fricative} },
  { letter: "ʟ̝", features: %w{pulmonic voiced velar lateral fricative} },
  { letter: "l̥", features: %w{pulmonic voiceless alveolar lateral approximant} },
  { letter: "l", features: %w{pulmonic voiced alveolar lateral approximant} },
  { letter: "ɭ", features: %w{pulmonic voiced retroflex lateral approximant} },
  { letter: "ʎ̟", features: %w{pulmonic voiced alveolo_palatal lateral approximant} },
  { letter: "ʎ", features: %w{pulmonic voiced palatal lateral approximant} },
  { letter: "ʟ", features: %w{pulmonic voiced velar lateral approximant} },
  { letter: "ɺ", features: %w{pulmonic voiced alveolar lateral flap} },
  { letter: "ɺ̢", features: %w{pulmonic voiced retroflex lateral flap} },
  { letter: "ʎ̯", features: %w{pulmonic voiced palatal lateral flap} },
  { letter: "ʟ̆", features: %w{pulmonic voiced velar lateral flap} },
]

NON_PULMONIC_CONSONANTS= [
  { letter: "ʘ", features: %w{bilabial click} },
  { letter: "ǀ", features: %w{dental click} },
  { letter: "ǃ", features: %w{alveolar click} },
  { letter: "ǂ", features: %w{palatal click} },
  { letter: "ǁ", features: %w{lateral click} },
  { letter: "ʘ̃", features: %w{nasal click} },
  { letter: "ʘ̃ˀ", features: %w{glottal click} },
  { letter: "‼", features: %w{retroflex click} },
  { letter: "ɓ̥", features: %w{voiceless bilabial implosive} },
  { letter: "ɓ", features: %w{voiced bilabial implosive} },
  { letter: "ɗ̥", features: %w{voiceless alveolar implosive} },
  { letter: "ɗ", features: %w{voiced alveolar implosive} },
  { letter: "ᶑ", features: %w{voiced retroflex implosive} },
  { letter: "ʄ̊", features: %w{voiceless palatal implosive} },
  { letter: "ʄ", features: %w{voiced palatal implosive} },
  { letter: "ɠ", features: %w{voiced velar implosive} },
  { letter: "ʛ", features: %w{voiceless uvular implosive} },
]

EJECTIVES = [
  { letter: "pʼ", features: %w{} },
  { letter: "t̪ʼ", features: %w{} },
  { letter: "tʼ", features: %w{} },
  { letter: "ʈʼ", features: %w{} },
  { letter: "cʼ", features: %w{} },
  { letter: "kʼ", features: %w{} },
  { letter: "qʼ", features: %w{} },
  { letter: "fʼ", features: %w{} },
  { letter: "θʼ", features: %w{} },
  { letter: "sʼ", features: %w{} },
  { letter: "ɬʼ", features: %w{} },
  { letter: "ʃʼ", features: %w{} },
  { letter: "ʂʼ", features: %w{} },
  { letter: "ɕʼ", features: %w{} },
  { letter: "xʼ", features: %w{} },
  { letter: "χʼ", features: %w{} },
  { letter: "tsʼ", features: %w{} },
  { letter: "tɬʼ", features: %w{} },
  { letter: "cʎ̝̥ʼ", features: %w{} },
  { letter: "tʃʼ", features: %w{} },
  { letter: "ʈʂʼ", features: %w{} },
  { letter: "kxʼ", features: %w{} },
  { letter: "kʟ̝̊ʼ", features: %w{} },
  { letter: "qχʼ", features: %w{} },
]
AFFRICATES = [
  { letter: "p̪f", features: %w{pulmonic voiceless labio_dental affricate} },
  { letter: "b̪v", features: %w{pulmonic voiced labio_dental affricate} },
  { letter: "ts", features: %w{pulmonic voiceless alveolar sibilant affricate} },
  { letter: "dz", features: %w{pulmonic voiced alveolar sibilant affricate} },
  { letter: "t̪s̪", features: %w{pulmonic voiceless dental sibilant affricate} },
  { letter: "d̪z̪", features: %w{pulmonic voiced dental sibilant affricate} },
  { letter: "tθ", features: %w{pulmonic voiceless dental affricate} },
  { letter: "dð", features: %w{pulmonic voiced dental affricate} },
  { letter: "tʃ", features: %w{pulmonic voiceless palatal alveolar affricate} },
  { letter: "dʒ", features: %w{pulmonic voiced palatal alveolar affricate} },
  { letter: "tɕ", features: %w{pulmonic voiceless alveolo_palatal affricate} },
  { letter: "dʑ", features: %w{pulmonic voiced alveolo_palatal affricate} },
  { letter: "ʈʂ", features: %w{pulmonic voiceless retroflex affricate} },
  { letter: "ɖʐ", features: %w{pulmonic voiced retroflex affricate} },
  { letter: "tɬ", features: %w{pulmonic voiceless alveolar lateral affricate} },
  { letter: "dɮ", features: %w{pulmonic voiced alveolar lateral affricate} },
  { letter: "cç", features: %w{pulmonic voiceless palatal affricate} },
  { letter: "ɟʝ", features: %w{pulmonic voiced palatal affricate} },
  { letter: "cʎ̥˔", features: %w{pulmonic voiceless palatal lateral affricate} },
  { letter: "kx", features: %w{pulmonic voiceless velar affricate} },
  { letter: "ɡɣ", features: %w{pulmonic voiced velar affricate} },
  { letter: "kʟ̝̊", features: %w{pulmonic voiceless velar lateral affricate} },
  { letter: "ɡʟ̝", features: %w{pulmonic voiced velar lateral affricate} },
  { letter: "qχ", features: %w{pulmonic voiceless uvular affricate} },
  { letter: "ɢʁ", features: %w{pulmonic voiceless uvular affricate} },
]

COARTICULATED_CONSONANTS=[
  { letter: "ʍ", features: %w{coarticulated pulmonic voiceless labial velar approximant} },
  { letter: "w", features: %w{coarticulated pulmonic voiced labial velar approximant} },
  { letter: "ɥ", features: %w{coarticulated pulmonic voiced labial palatal approximant} },
  { letter: "ɧ", features: %w{coarticulated pulmonic voiceless palatal alveolar fricative} },
  { letter: "k͡p", features: %w{coarticulated pulmonic voiceless labial velar stop} },
  { letter: "ɡ͡b", features: %w{coarticulated pulmonic voiced labial velar stop} },
  { letter: "ŋ͡m", features: %w{coarticulated pulmonic voiced labial velar nasal} },
]

CONSONANTS = (
  PULMONIC_CONSONANTS +
  NON_PULMONIC_CONSONANTS +
  # EJECTIVES +
  AFFRICATES +
  COARTICULATED_CONSONANTS
)

