
VOWELS = [
  { letter: "i", features: %w{close front unrounded} },
  { letter: "y", features: %w{close front rounded} },
  { letter: "ɨ", features: %w{close central unrounded} },
  { letter: 'ʉ', features: %w{close central unrounded} },
  { letter: 'ɯ', features: %w{back close unrounded} },
  { letter: 'u', features: %w{back close rounded} },
  { letter: 'ɪ', features: %w{near_close near_front unrounded} },
  { letter: 'ʏ', features: %w{near_close near_front rounded} },
  { letter: 'ʊ', features: %w{near_close near_back rounded} },
  { letter: 'e', features: %w{close_mid front unrounded} },
  { letter: 'ø', features: %w{close_mid front rounded} },
  { letter: 'ɘ', features: %w{close_mid central unrounded} },
  { letter: 'ɵ', features: %w{close_mid central rounded} },
  { letter: 'ɤ', features: %w{close_mid back unrounded} },
  { letter: 'o', features: %w{close_mid back rounded} },
  { letter: 'ə', features: %w{mid central unrounded} },
  { letter: 'ɛ', features: %w{open_mid front unrounded} },
  { letter: 'œ', features: %w{open_mid front rounded} },
  { letter: 'ɜ', features: %w{open_mid central unrounded} },
  { letter: 'ɞ', features: %w{open_mid central rounded} },
  { letter: 'ʌ', features: %w{open_mid back unrounded} },
  { letter: 'ɔ', features: %w{open_mid back rounded} },
  { letter: 'æ', features: %w{near_open front unrounded} },
  { letter: 'ɐ', features: %w{near_open central unrounded} },
  { letter: 'a', features: %w{open front unrounded} },
  { letter: 'ɶ', features: %w{open front rounded} },
  { letter: 'ä', features: %w{open central unrounded} },
  { letter: 'ɑ', features: %w{open back unrounded} },
  { letter: 'ɒ', features: %w{open back rounded} },
]
