
VOWELS = [
  { letter: "i", features: %w{high front unrounded} },
  { letter: "y", features: %w{high front rounded} },
  { letter: "ɨ", features: %w{high central unrounded} },
  { letter: 'ʉ', features: %w{high central unrounded} },
  { letter: 'ɯ', features: %w{back high unrounded} },
  { letter: 'u', features: %w{back high rounded} },
  { letter: 'ɪ', features: %w{near_high near_front unrounded} },
  { letter: 'ʏ', features: %w{near_high near_front rounded} },
  { letter: 'ʊ', features: %w{near_high near_back rounded} },
  { letter: 'e', features: %w{high_mid front unrounded} },
  { letter: 'ø', features: %w{high_mid front rounded} },
  { letter: 'ɘ', features: %w{high_mid central unrounded} },
  { letter: 'ɵ', features: %w{high_mid central rounded} },
  { letter: 'ɤ', features: %w{high_mid back unrounded} },
  { letter: 'o', features: %w{high_mid back rounded} },
  { letter: 'ə', features: %w{mid central unrounded} },
  { letter: 'ɛ', features: %w{low_mid front unrounded} },
  { letter: 'œ', features: %w{low_mid front rounded} },
  { letter: 'ɜ', features: %w{low_mid central unrounded} },
  { letter: 'ɞ', features: %w{low_mid central rounded} },
  { letter: 'ʌ', features: %w{low_mid back unrounded} },
  { letter: 'ɔ', features: %w{low_mid back rounded} },
  { letter: 'æ', features: %w{near_low front unrounded} },
  { letter: 'ɐ', features: %w{near_low central unrounded} },
  { letter: 'a', features: %w{low front unrounded} },
  { letter: 'ɶ', features: %w{low front rounded} },
  { letter: 'ä', features: %w{low central unrounded} },
  { letter: 'ɑ', features: %w{low back unrounded} },
  { letter: 'ɒ', features: %w{low back rounded} },
]
