DIACRITICS = [
  { letter: "̩", feature_name: "", examples: "ɹ̩ n̩", description: "Syllabic" },
  { letter: "̯", feature_name: "", examples: "e̯ ʊ̯", description: "Non-syllabic" },
  { letter: "ʰ", feature_name: "aspirated", examples: "tʰ", description: "Aspirated" },
  { letter: "̚", feature_name: "", examples: "d̚", description: "No audible release" },
  { letter: "ʱ", feature_name: "", examples: "dʱ", description: "Breathy Aspirated" },
  { letter: "ⁿ", feature_name: "nasal", examples: "dⁿ", description: "Nasal release" },
  { letter: "ˡ", feature_name: "lateral", examples: "dˡ", description: "Lateral release" },
  { letter: "̥", feature_name: "voiceless", examples: "n̥ d̥", description: "Voiceless" },
  { letter: "̬", feature_name: "voiced", examples: "s̬ t̬", description: "Voiced" },
  { letter: "̤", feature_name: "", examples: "b̤ a̤", description: "Breathy voiced" },
  { letter: "̰", feature_name: "", examples: "b̰ a̰", description: "Creaky voiced" },
  { letter: "̪", feature_name: "dental", examples: "t̪ d̪", description: "Dental" },
  { letter: "̼", feature_name: "", examples: "t̼ d̼", description: "Linguolabial" },
  { letter: "̺", feature_name: "", examples: "t̺ d̺", description: "Apical" },
  { letter: "̻", feature_name: "", examples: "t̻ d̻", description: "Laminal" },
  { letter: "̟", feature_name: "", examples: "u̟ t̟", description: "Advanced" },
  { letter: "̠", feature_name: "", examples: "i̠ t̠", description: "Retracted" },
  { letter: "̈", feature_name: "", examples: "ë ä", description: "Centralized" },
  { letter: "̽", feature_name: "", examples: "e̽ ɯ̽", description: "Mid-centralized" },
  { letter: "̝", feature_name: "", examples: "e̝ ɹ̝", description: "Raised (ɹ̝ = voiced alveolar nonsibilant fricative)" },
  { letter: "̞", feature_name: "", examples: "e̞ β̞", description: "Lowered (β̞ = bilabial approximant)" },
  { letter: "̹", feature_name: "rounded", examples: "ɔ̹ x̹", description: "More rounded" },
  { letter: "̜", feature_name: "unrounded", examples: "ɔ̜ x̜ʷ", description: "Less rounded" },
  { letter: "ʷ", feature_name: "labial", examples: "tʷ dʷ", description: "Labialized or labio-velarized" },
  { letter: "ʲ", feature_name: "palatal", examples: "tʲ dʲ", description: "Palatalized" },
  { letter: "ˠ", feature_name: "velar", examples: "tˠ dˠ", description: "Velarized" },
  { letter: "ˤ", feature_name: "pharyngeal", examples: "tˤ aˤ", description: "Pharyngealized" },
  { letter: "ᶣ", feature_name: "", examples: "tᶣ dᶣ", description: "Labio-palatalized" },
  { letter: "̴", feature_name: "velar", examples: "ɫ z̴", description: "Velarized or pharyngealized" },
  { letter: "̘", feature_name: "", examples: "e̘ o̘", description: "Advanced tongue root" },
  { letter: "̙", feature_name: "", examples: "e̙ o̙", description: "Retracted tongue root" },
  { letter: "̃", feature_name: "nasal", examples: "ẽ z̃", description: "Nasalized" },
  { letter: "˞", feature_name: "", examples: "ɚ ɝ", description: "Rhotacized" },
]
